version: '3.8'

services:
  fastapi_app:
    build: .
    container_name: resumes_app
    restart: always
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/resumes_db
    networks:
      - resumes_network

  db:
    image: postgres:15
    container_name: resumes_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: resumes_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - resumes_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d resumes_db"]
      interval: 5s
      retries: 5
      timeout: 5s

volumes:
  db_data:

networks:
  resumes_network:
    driver: bridge
